spring:
  application:
    name: quota-service
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      hibernate:
        ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2

---
spring:
  config:
    activate:
      on-profile: cloud
  datasource:
    url: jdbc:mysql://localhost:3306/yourdb
    username: yourusername
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

quota:
  keyPrefix: "user:quota:"
  maxRequestsPerUser: 5
